(()=>{const API="https://djbrmswvlmivvltcsstr.supabase.co/functions/v1/analysis-feed",ENGINE="https://djbrmswvlmivvltcsstr.supabase.co/functions/v1/forecast-engine",
esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),
pct=n=>Math.round((Number(n)||0)*100),
fmt=t=>new Date(t).toLocaleString("sv-SE",{timeZone:"Europe/Stockholm",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}),
camName=s=>String(s||"Okänd").replace("PRO- 1 Ekön","PRO-1 Ekön"),
tm=t=>t?new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Stockholm",hour:"2-digit",minute:"2-digit"}).format(new Date(t)):"–";
function forecastSummary(title,f){if(!f)return '<div class="row"><span>'+title+'</span><b>Ingen prognos ännu</b></div>';return '<div class="row"><span>'+title+'</span><div style="display:flex;gap:10px;font-weight:800"><span class="'+(f.forecast_level==="Låg"?"accent":"muted")+'">Låg</span><span class="'+(f.forecast_level==="Medel"?"accent":"muted")+'">Medel</span><span class="'+(f.forecast_level==="Hög"?"accent":"muted")+'">Hög</span></div></div><div class="small" style="margin:2px 0 12px">Starkaste signal: <b>'+esc(camName(f.camera_name))+' · '+tm(f.window_start)+'–'+tm(f.window_end)+'</b> · prognospoäng '+esc(f.forecast_score)+'/100</div>'}
async function load(){
 const host=document.getElementById("viltiq-live-analysis");if(!host)return;
 try{
  await fetch(ENGINE+"?t="+Date.now(),{cache:"no-store"}).catch(()=>{});
  const r=await fetch(API+"?t="+Date.now(),{cache:"no-store"}),d=await r.json();if(!d.ok)throw Error();
  const rs=d.recent||[],week=d.week||[],ev=(d.liveEvents||d.events||[]).slice(),now=Date.now();
  const recentEvents=ev.filter(e=>now-new Date(e.event_end||e.event_start).getTime()<=864e5).sort((a,b)=>new Date(b.event_end||b.event_start)-new Date(a.event_end||a.event_start));
  const bt=recentEvents.reduce((x,e)=>(x.n+=Number(e.animal_count||0),x.m+=Number(e.male_count||0),x.f+=Number(e.female_count||0),x.c+=Number(e.calf_count||0),x.u+=Number(e.unknown_count||0),x),{n:0,m:0,f:0,c:0,u:0});
  const by={};for(const e of recentEvents){const k=camName(e.camera_name);by[k]=(by[k]||0)+1}const top24=Object.entries(by).sort((a,b)=>b[1]-a[1])[0];
  const runs=d.forecastRuns||[],latest={};for(const f of runs){if(!latest[f.animal_type])latest[f.animal_type]=f}
  let h='<div class="card"><div class="section-label">NULÄGE · SENASTE 24 H · LIVE</div><h2>Vad händer på marken?</h2><div class="kpi"><div><b>'+recentEvents.length+'</b><br><span class="muted small">Oberoende besök</span></div><div><b>'+bt.m+'</b><br><span class="muted small">Hjortar</span></div><div><b>'+bt.f+'</b><br><span class="muted small">Hindar</span></div><div><b>'+bt.c+'</b><br><span class="muted small">Kalvar</span></div></div>'+(top24?'<div class="row"><span>Aktivast senaste dygnet</span><b>'+esc(top24[0])+' · '+top24[1]+' besök</b></div>':'')+'<p class="note">Bygger på oberoende AI-tolkade kamerabesök, inte antal bilder.</p></div>';
  h+='<div class="card forecast"><div class="section-label">AI-JAKTPROGNOS · LIVE</div><h2>Kommande 24 timmar</h2>'+forecastSummary("Hjort",latest.buck)+forecastSummary("Hind &amp; Kalv",latest.hind_calf)+'<p class="note">Samma forecast-engine används här och på Prognos-fliken. Start visar en kort sammanfattning av exakt samma prognosresultat.</p></div>';
  h+='<div class="card"><div class="section-label">SENASTE OBSERVATIONER · LIVE</div><h2>Det senaste AI:n sett</h2>';
  if(recentEvents.length){recentEvents.slice(0,3).forEach(e=>{const parts=[];if(e.male_count)parts.push(e.male_count+" hjort");if(e.female_count)parts.push(e.female_count+" hind");if(e.calf_count)parts.push(e.calf_count+" kalv");if(e.unknown_count)parts.push(e.unknown_count+" okänd");h+='<div class="row"><div><b>'+esc(camName(e.camera_name))+' · '+fmt(e.event_end||e.event_start)+'</b><div class="muted small">'+esc(parts.join(" · ")||((e.animal_count||0)+" djur"))+'</div></div><span class="badge">'+pct(e.confidence)+'%</span></div>'})}else h+='<div class="row"><span>Inga observationer senaste dygnet</span><b>–</b></div>';
  h+='<p class="note">Visar de tre senaste oberoende besöken och AI:ns klassning.</p></div>';
  host.innerHTML=h;
  const dev=document.getElementById("viltiq-dev-status");if(dev){dev.innerHTML='<div class="card"><div class="section-label">AI-STATUS · UTVECKLING</div><h2>'+Number(d.analyzed||0)+' analyser klara · '+Number(d.queued||0)+' i kö</h2><div class="row"><span>Oberoende händelser totalt</span><b>'+ev.length+'</b></div><p class="note">Teknisk status för utveckling och felsökning. Behöver inte ligga på Start.</p></div>'}
  const invHost=document.getElementById("viltiq-inventory-info");if(invHost){const w=week.filter(a=>a.camera_images?.captured_at&&now-new Date(a.camera_images.captured_at)<=7*864e5),it=w.reduce((x,a)=>(x.m+=a.male_count||0,x.f+=a.female_count||0,x.c+=a.calf_count||0,x.u+=a.unknown_count||0,x),{m:0,f:0,c:0,u:0});invHost.innerHTML='<div class="card"><div class="section-label">INVENTERING · UNDER UTVÄRDERING</div><h2>Senaste 7 dygnen</h2><div class="row"><span>Hindar</span><b>'+it.f+'</b></div><div class="row"><span>Kalvar</span><b>'+it.c+'</b></div><div class="row"><span>Hjortar</span><b>'+it.m+'</b></div>'+(it.u?'<div class="row"><span>Okända</span><b>'+it.u+'</b></div>':'')+'<p class="note">Den här vyn summerar AI-tolkningen per bild och kan därför räkna samma djur flera gånger. Den ligger tillfälligt under Info medan vi avgör om den ska byggas om eller tas bort.</p></div>'}
 }catch(e){host.innerHTML='<div class="card"><b>Liveanalysen kunde inte hämtas.</b></div>'}
}
document.addEventListener("DOMContentLoaded",load);setInterval(load,60000)})();